### PR TITLE
Updated to the latest version of Jersey

### PR DESCRIPTION
**Pull request by jalbr74**
So far, I haven't run into any problems changing the version to 2.22.1.  I performed a clean build, and verified I could hit the following service successfully:
/sspr/public/rest/app-data/audit

According to some resources online, the container filters and POJO mapping init params were no longer needed, so I removed them.

@jrivard Please review and merge

### CODE REVIEW

**Comment by jrivard** [comment]
All rest services are returning 404 with this branch.  Particularly /public/rest/status and /public/rest/app-data/client

**Comment by jalbr74** [comment]
@jrivard Ok, looks like this addresses the gzip content encoding, and the warning we were seeing on Friday.  Please review and merge.

**Comment by jrivard** [comment]
Still seeing this warning: 10-Feb-2016 14:48:00.979 WARNING [http-nio-8080-exec-8] org.glassfish.jersey.servlet.WebComponent.filterFormParameters A servlet request to the URI http://localhost:8080/sspr/public/rest/app-data/strings/Display?etag=c1fdc577b370853fe25ff3111b3742b1f4db5696 contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.

**Comment by jalbr74** [comment]
I've been able to duplicate the warnings not only in this branch, but in master as well.  So I don't think the problem is related to updating the Jersey libraries.

From what I've tried and what I've read, it seems you can't reliably change the log level for loggers programmatically, as we're trying to do in PwmLogManager.java.  You can kind of get it to work, but then you see unexpected behavior.  I've seen many posts recommend disabling java.util.logging, or using one of the many bridges (such as the slf4j bridge) to replace the functionality provided by java.util.logging.

It seems we're not really using java.util.logging anyway, so I went ahead and disabled it.  Let me know if you'd rather it be kept, and I'll look into non-programmatic ways of configuring java.util.logging to raise the log level for jersey.

@jrivard Please review and merge.

**Comment by jalbr74** [comment]
Ok Jason.  Give this a try.  On my machine I can go from seeing a ton of warning messages about the "form parameters in the request body", to nothing at all.  Hopefully you'll see the same results.

@jrivard Please review and merge.

**Comment by jrivard** [comment]
I no longer see the errors, that seems resolved.  However the changepassword page is not functioning properly.  The /checkpassword rest api is failing with an error

**Comment by jalbr74** [comment]
Looks like an extra library was needed for requests that POST a JSON object to the server, and get converted into a Java POJO.

@jrivard Please review and merge

**Pull request merged**
