### PR TITLE
Fuzzy match validation

### PR DESCRIPTION
**Pull request by hsssystems**
LDAP attributes based validation depends heavily on the quality/style of data in LDAP. Names, cities and streetnames may be entered in many different ways. In the Unit Test are examples like the following

Saint-Just-en-Chaussée and saint just-en-chaussee

In many cases different spelling for the same attribute value may be possible. During validation it may be very error prone to find out the LDAP saved spelling for the user.

This patch is an first approach to handle this issue by normalizing user supplied data and LDAP data and then compare the values. 

It still misses a UI component for the fuzzyMatch checkbox that would require some logic because the setting makes only sense in validation contexts and e.g. not in search contexts (not possible).

### CODE REVIEW

**Comment by jrivard** [comment]
i like this but...  I'm uncomfortable adding a library that isn't published on maven central (or some other common repository).  Are you the owner of this library or can you encourage the auther to publish?  Are the alternates that may be are more mature?

I think there are serious security downsides with using this, but so long as it is admin-enabled and not enabled by default and the admin is warned in the setting text that's acceptable. 

this could probably be generalized to other forms, such as c/r and user activation.

**Comment by hsssystems** [comment]
I asked for publishing the project (I am not the owner)

https://github.com/gcardone/junidecode/issues/3#issuecomment-299913811

An alternative (that I do not know / never tried) would be https://github.com/jirutka/unidecode

**Comment by hsssystems** [comment]
The owner is willing to publish:

https://github.com/gcardone/junidecode/issues/3#issuecomment-299917206

**Comment by jrivard** [comment]
closing request since library has never been published.

**Pull request closed without merging**
