### PR TITLE
Cas configuration update

### PR DESCRIPTION
**Pull request by idwright**
This replaces PR #79 

web.xml changes support the 'cas' profile and fix the template for more recent versions of the cas client.

The rest of the changes are to allow the configuration of the encryption of the password in the CAS validation response as per https://apereo.github.io/cas/4.2.x/integration/ClearPass.html

The point of this change is that you shouldn't need the proxyCallback URL any more (which is not supported in CAS 5 and greater any longer anyway - https://apereo.github.io/cas/5.1.x/integration/ClearPass.html). This configuration is left for support of old CAS servers (which will be out of support at the end of 2017)

I've tried to keep the changes as self contained as possible

The pom.xml changes create a new profile 'cas' which together with the cas.server and pwm.server properties can be used to configure for CAS integration without editing any files.

The idea behind the cas profile in the pom.xml is to make it easier to use the existing, documented, configuration changes to the web.xml - i.e. compile with a profile instead of editing the web.xml to enable the CAS filters - not ideal but a simple way to have conditional filters
An alternative might be to allow a jar containing a web-fragment.xml that configures the filters but that would require a more complex change to the web.xml so that the ordering can be managed (web.xml is always before any web-fragment.xml)
This would work without the pom.xml changes.

The rest of the changes are to allow the newish CAS technique for retrieving the password i.e. using public/private key encryption as part of the validation request instead of the clear pass callback method - ideally these would be in the pwm codebase (which is why I submitted a PR) - the biggest impact by far is providing somewhere to store the encryption key(and algorithm)

It's not immediately obvious how pwm can otherwise retrieve the credentials from CAS e.g. using OAuth

### CODE REVIEW

**Comment by jrivard** [comment]
Thanks for cleaning up and resubmitting.  I have two requests:

1) we don't need a tomcat executor in the maven build.   If you want this use a parent pom or a local script wrapper.

2) configuring the web.xml via maven is also not ideal.   I'd rather not have maven doing this.  It will either need to be done by hand after the maven build or better yet perhaps there are ways to do this at runtime and store the config in the configuration.xml?    It would be best not to have the servlet declared in the web.xml at all and just have it loaded via annotations like the other servlets.

Thanks!

**Comment by idwright** [comment]
I've removed the tomcat executor and the cas profile which puts it back to the original method of configuring the web.xml by hand.

This relies on https://github.com/apereo/java-cas-client which uses filters not servlets

I agree that editing the web.xml is far from ideal - in other projects I've used a separate jar with a web-fragment.xml but that relies on being able to process the filters in the right order - web.xml is always before any web-fragment and the ordering directive in web-fragment only relates to other fragments.
Annotations don't allow ordering at all.

There are other ways to configure CAS once you've got the filters enabled - see the github link above - I tend to use PROPERTIES_FILE rather then WEB_XML - but I was going for minimal changes in pwm and it does always come back to getting the filters enabled first in the filter chain.

If you've any suggestions how to get the CAS filters processed first without modifying web.xml I would be very happy to know - it seems that moving other filters, e.g. AuthenticationFilter, into a different fragment/jar is too big a change for me

**Comment by jrivard** [comment]
Thanks for the updates idwright.  I've still got some things I need to change here but in the interest of moving things along I'm going to merge this now.  A couple things I'll be changing shortly:

- removing properties for cas from pom.xml, 
- making the CAS auth filter loadable via reflection

I guess I should have been more explicit that I'm trying to keep CAS like a pluggable module that can be easily removed, there are downstream projects based on PWM where cas support is not desirable and is removed.  So watch out for a few changes and let me know if anything breaks this implementation.  Unfortunately I have no way to test if things actually work with CAS.

**Comment by idwright** [comment]
Thanks for merging this.
I completely agree with trying to keep CAS as pluggable as possible - I was trying to keep these changes as independent as possible.

I think there are four things key to this:
1. A way to inject the authentication filters before the pwm filters
2. How to get the password credentials into CAS
3. How to configure the decryption
4. Configuring the CAS filters - there are quite a lot of options

**Comment by Jognu** [comment]
Nice to see this update !

Someone managed to make it work?

I tried to make it works with the last release (I have it that works with the old @idwright fork).

But I always get an error "5001 ERROR_WRONGPASSWORD (error during CAS authentication attempt: 5001 ERROR_WRONGPASSWORD (CAS server did not return credentials for user 'XX'))

I set configurationStrategy to WEB_XML in the web.xml, and no configFileLocation.
I uncommented everything related to CAS and filled like in the @idwright fork.
With proxyCallbackUrl empty to use the new method.

In PWM I let the clearpass URL empty and set the certificate.

Did I missed something which is different with this version ?

**Comment by Jognu** [comment]
I found the error, it's on web.xml : org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter should be org.jasig.cas.client.validation.Cas30ProxyReceivingTicketValidationFilter

**Pull request merged**
