### PR TITLE
Changed the language selector at the bottom of the page from an butto…

### PR DESCRIPTION
**Pull request by rkeil-git**
…n to a span to stop if being selected when the enter key is hit on the help page when running in IE.

### CODE REVIEW

**Comment by rkeil-git** [comment]
Fixed the token service to start at the appropriate time to work with the command line rest calls.
Updated the Shortcut Header help to have more clarification about how it works.
Removed the link in the email verification email and will be putting it back in the 4.3 release.

**Comment by rkeil-git** [comment]
Fixed the Statistics Manager to start during runtime.

**Comment by rkeil-git** [comment]
fixed the ability to change your password before the minimum lifetime password reset time is up before the minimum time is reached

**Comment by rkeil-git** [comment]
Backed out the previous change.

**Comment by rkeil-git** [comment]
Fixed the syslog entries to accept and try multiple entries

**Comment by jrivard** [comment]
Closing this pull request as the content is being submitted in another request(s).

**Pull request closed without merging**
