### PR TITLE
Update Error_nn.properties

### PR DESCRIPTION
**Pull request by ilyse63**
Updated strings and fixed encoding of Norwegian characters

### CODE REVIEW

**Comment by jrivard** [comment]
Are you able to fix merge conflict?

**Comment by torharaldlothe** [comment]
Hi Jason! 
On behalf of some Norwegian customers I am trying to pick up this process to have Norwegian Nynorsk (nn) translation completed for PWM / SSPR 4.5. Ivar Lyse has left Micro Focus, so that is why this is uncompleted. So where do I go from here? Best regards Tor Harald Lothe

**Comment by jrivard** [comment]
@torharaldlothe you can update the branch and resolve the conflict.  If your unfamiliar with git, it might be easier to close this this pull request and use the web interface to edit the file and have git create a new pull request.

**Comment by torharaldlothe** [comment]
@jrivard I have no idea where to start here; I guess there is a tool that encodes the Norwegian special chars in some way it seems? Or is that done automatically in the web interface? Any help and pointers mostly appreciated :)

**Comment by oddkl** [comment]
@jrivard You can close this pull request, and I'll create a new one shortly. I have together with @torharaldlothe and Hans Førde updated both Norwegian Bokmål (nb) and Norwegian Nynorsk (nn)

**Pull request closed without merging**
