### PR TITLE
Fix misleading error message for Password_SameAsAttr

### PR DESCRIPTION
**Pull request by mattock**
By default Pwm checks if the password contains cn, sn or givenName. When any of
these are allowed to be short (e.g. 2 characters), the likelihood of a long,
strong password consisting of random characters matching any of those is big. So
do not tell the user that password is "too obvious" if it happens to contain a
user attribute by accident. Rather give the user a better idea of the problem so
that he/she can fix it.

### CODE REVIEW

**Comment by mattock** [comment]
This fixes https://github.com/pwm-project/pwm/issues/360. Translations (except Finnish which I fixed) still have the problem, though.

**Comment by jrivard** [comment]
I agree the old message is too basic, but normal people don't know what an 'attribute' is......

**Comment by mattock** [comment]
@jrivard agreed, but I could figure out any better way to express the problem. What about adding an example at the end along these lines: "New password contains a user attribute such as name or email"?

**Comment by jrivard** [comment]
Unfortunately, the above suggestion doesn't always work because the policy could be configured differently than the text reads.  Thus I think it's best to leave the default string generic and ambiguous.  The admin can override it in configuration if needed..

**Pull request closed without merging**
