### PR TITLE
CAS configuration update

### PR DESCRIPTION
**Pull request by idwright**
Changes to support issue #78 

The pom.xml changes create a new profile 'cas' which together with the cas.server and pwm.server properties can be used to configure for CAS integration without editing any files.

web.xml changes support the 'cas' profile and fix the template for more recent versions of the cas client.

The rest of the changes are to allow the configuration of the encryption of the password in the CAS validation response as per [https://apereo.github.io/cas/4.2.x/integration/ClearPass.html](https://apereo.github.io/cas/4.2.x/integration/ClearPass.html)

I've tried to keep the changes as self contained as possible

### CODE REVIEW

**Comment by JasonEverling** [comment]
@idwright Will you be making a change for CAS 5 once it is released? The 'credentials' are now released through the /p3/serviceValidate response. It doesn't look like much needs to change except on line 107 the URL code but since you updated for CAS 4 you might be able to get it to work with CAS 5?

[(https://github.com/pwm-project/pwm/blob/master/src/main/java/password/pwm/util/CASFilterAuthenticationProvider.java#L107)

**Comment by idwright** [comment]
I will check against CAS 5 but the credentials are released in the validate response back to at least 4.1 and this code supports that - there are changes to the settings to store the key used to decrypt the credentials.

**Comment by JasonEverling** [comment]
@idwright Do you know the URL to use for CAS v5 might be? There is no longer a clearPass URL ( https://cas.domain.edu/cas/clearPass ) like there was previously. Would I just enter https://cas.domain.edu/cas/p3/serviceValidate instead?

**Comment by idwright** [comment]
You are correct that there is no longer a clearPass URL

The password is released as part of the serviceValidate request

You will need to configure CAS so that it releases the password for you, and make sure that PWM is configured so that it can decrypt the value returned from CAS

**Comment by jrivard** [comment]
I don't think having feature-specific builds makes sense.  Why cant these changes be made within the pwm codebase?  I'm also still not sure why PWM really needs CAS support given the OAuth support now in pwm....

**Comment by wrighting** [comment]
The idea behind the cas profile in the pom.xml is to make it easier to use the existing, documented, configuration changes to the web.xml - i.e. compile with a profile instead of editing the web.xml to enable the CAS filters - not ideal but a simple way to have conditional filters

The rest of the changes are to allow the newish CAS technique for retrieving the password i.e. using public/private key encryption as part of the validation request instead of the clear pass method - ideally these would be in the pwm codebase (which is why I submitted a PR) - the biggest impact by far is providing somewhere to store the encryption key.

It's not immediately obvious how pwm can otherwise retrieve the credentials from CAS e.g. using OAuth

Thanks

**Comment by idwright** [comment]
The idea behind the cas profile in the pom.xml is to make it easier to use the existing, documented, configuration changes to the web.xml - i.e. compile with a profile instead of editing the web.xml to enable the CAS filters - not ideal but a simple way to have conditional filters

The rest of the changes are to allow the newish CAS technique for retrieving the password i.e. using public/private key encryption as part of the validation request instead of the clear pass method - ideally these would be in the pwm codebase (which is why I submitted a PR) - the biggest impact by far is providing somewhere to store the encryption key.

It's not immediately obvious how pwm can otherwise retrieve the credentials from CAS e.g. using OAuth

Thanks

**Comment by Jognu** [comment]
It would be great to merge this since the oAuth method is not well documented and may not work with CAS.

**Comment by JasonEverling** [comment]
@Jognu Its not even really the oauth config but getting the current users password in oauth for transparent pwm checkAll integration between application logins to check policies, expiration, update profile, change their expired password, or any other operation that requires the current password. Does oauth spec even support password attribute?

**Comment by Jognu** [comment]
Hi @idwright 
Did you modifications works with CAS > 5.0 ?

I try to make it work with 5.1.1, but I have an error on PWM : "The supplied proxy callback URL could not be authenticated. Either cannot be reached, it is not allowed to exercise proxy authentication."

The URL seems good (pwm/proxyCallback).

Thanks a lot.

**Comment by idwright** [comment]
The point of this change is that you shouldn't need the proxyCallback URL any more (which is not supported in CAS 5 and greater any longer anyway - https://apereo.github.io/cas/5.1.x/integration/ClearPass.html)

By specifying the encryption key and algorithm it's possible to decrypt the credentials supplied in the CAS validation response.
(See https://github.com/idwright/pwm/commit/dfd14b4ad30cb6d8c58f7e52f6fd84231156c8f3 although that's not the final version of the files it's probably the easiest commit to look at to get a feel for the changes)

You need to configure the CAS attribute release policy (https://apereo.github.io/cas/5.1.x/integration/Attribute-Release-Policies.html) with authorizedToReleaseCredentialPassword and publicKey

**Comment by Jognu** [comment]
@idwright Thanks for your help, it works !
I was thinking that your code need modifications but not, it is compatible.
I just need to configure CAS like you said (generate key, configure public key in CAS, configure the service).
And then in PWM import the key and configure the encryption method (with the clearpass URL empty).

This pull request should really be accepted, PWM is a really good tool and it's perfect with CAS.

**Comment by idwright** [comment]
Glad to know it works for somebody else, and on 5.1, and they'd like the PR accepted (happy to work towards getting it merged but don't really know why it hasn't been)

Keeping the clearpass URL setting is potentially confusing but I didn't want to remove the support for that especially as CAS v4 is still supported until the end of this year

**Comment by jrivard** [comment]
at this point because of the long history on this pull request i can't really tell what's different.  Can you cancel this request and re-submit a new one that is current?

**Comment by idwright** [comment]
Replaced by #193 due to the age of the PR

**Pull request closed without merging**
